CREATE TABLE IF NOT EXISTS users
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name   VARCHAR(255) NOT NULL,
    email  VARCHAR(255) NOT NULL,
    rating INTEGER      NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_user UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_category UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pinned BOOLEAN NOT NULL,
    title  VARCHAR(255),
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lat DECIMAL NOT NULL,
    lon DECIMAL NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    annotation         TEXT                 NOT NULL,
    category_id        BIGINT,
    confirmed_requests INTEGER              NOT NULL,
    created_on         TIMESTAMP            NOT NULL,
    description        TEXT                 NOT NULL,
    event_date         TIMESTAMP            NOT NULL,
    initiator_id       BIGINT               NOT NULL,
    location_id        BIGINT               NOT NULL,
    paid               BOOLEAN              NOT NULL,
    participant_limit  INTEGER              NOT NULL,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN DEFAULT TRUE NOT NULL,
    state              VARCHAR(255),
    title              VARCHAR(255),
    views              INTEGER              NOT NULL,
    rating             INTEGER              NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id),
    FOREIGN KEY (category_id) REFERENCES categories (id),
    FOREIGN KEY (initiator_id) REFERENCES users (id),
    FOREIGN KEY (location_id) REFERENCES locations (id)
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    CONSTRAINT pk_compilations_events PRIMARY KEY (id),
    FOREIGN KEY (compilation_id) REFERENCES compilations (id),
    FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id     BIGINT       NOT NULL,
    requester_id BIGINT       NOT NULL,
    status       VARCHAR(255) NOT NULL,
    created      TIMESTAMP    NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id),
    CONSTRAINT uq_request UNIQUE (event_id, requester_id),
    FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reactions
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id  BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    CONSTRAINT pk_reactions PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);