version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    volumes:
      - /var/log/stats-server
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats-service
      - POSTGRES_USER=kitty
      - POSTGRES_PASSWORD=purrrrrr
    restart: on-failure

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ewm-stats-service
      - POSTGRES_USER=kitty
      - POSTGRES_PASSWORD=purrrrrr

  ewm-service:
    build: ./main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    volumes:
      - /var/log/main-server
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main-service
      - POSTGRES_USER=kitty
      - POSTGRES_PASSWORD=purrrrrr
    restart: on-failure

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-main-db
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ewm-main-service
      - POSTGRES_USER=kitty
      - POSTGRES_PASSWORD=purrrrrr
