version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    volumes:
      - /var/log/server
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats-service
      - POSTGRES_USER=kitty
      - POSTGRES_PASSWORD=purrrrrr

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ewm-stats-service
      - POSTGRES_USER=kitty
      - POSTGRES_PASSWORD=purrrrrr

  ewm-service:
    build: ./main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    volumes:
      - /var/log/server
#    depends_on:
#      - ewm-db

#  ewm-db:
#    image: postgres:14-alpine
